// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: autor.sql

package db

import (
	"context"
	"database/sql"
)

const createAutor = `-- name: CreateAutor :one
INSERT INTO Autor (nombre, pais, fecha_nacimiento, biografia) 
VALUES ($1, $2, $3, $4) 
RETURNING id_autor, nombre, pais, fecha_nacimiento, biografia
`

type CreateAutorParams struct {
	Nombre          string
	Pais            sql.NullString
	FechaNacimiento sql.NullTime
	Biografia       sql.NullString
}

func (q *Queries) CreateAutor(ctx context.Context, arg CreateAutorParams) (Autor, error) {
	row := q.db.QueryRowContext(ctx, createAutor,
		arg.Nombre,
		arg.Pais,
		arg.FechaNacimiento,
		arg.Biografia,
	)
	var i Autor
	err := row.Scan(
		&i.IDAutor,
		&i.Nombre,
		&i.Pais,
		&i.FechaNacimiento,
		&i.Biografia,
	)
	return i, err
}

const deleteAutor = `-- name: DeleteAutor :exec
DELETE FROM Autor 
WHERE id_autor = $1
`

func (q *Queries) DeleteAutor(ctx context.Context, idAutor int32) error {
	_, err := q.db.ExecContext(ctx, deleteAutor, idAutor)
	return err
}

const getAutor = `-- name: GetAutor :one
SELECT FROM Autor 
WHERE id_autor = $1
`

type GetAutorRow struct {
}

func (q *Queries) GetAutor(ctx context.Context, idAutor int32) (GetAutorRow, error) {
	row := q.db.QueryRowContext(ctx, getAutor, idAutor)
	var i GetAutorRow
	err := row.Scan()
	return i, err
}

const listAutores = `-- name: ListAutores :many
SELECT id_autor, nombre, pais, fecha_nacimiento, biografia FROM Autor 
ORDER BY nombre
`

func (q *Queries) ListAutores(ctx context.Context) ([]Autor, error) {
	rows, err := q.db.QueryContext(ctx, listAutores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Autor
	for rows.Next() {
		var i Autor
		if err := rows.Scan(
			&i.IDAutor,
			&i.Nombre,
			&i.Pais,
			&i.FechaNacimiento,
			&i.Biografia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutor = `-- name: UpdateAutor :exec
UPDATE Autor 
SET nombre = $2, pais = $3, fecha_nacimiento = $4, biografia = $5
WHERE id_autor = $1
`

type UpdateAutorParams struct {
	IDAutor         int32
	Nombre          string
	Pais            sql.NullString
	FechaNacimiento sql.NullTime
	Biografia       sql.NullString
}

func (q *Queries) UpdateAutor(ctx context.Context, arg UpdateAutorParams) error {
	_, err := q.db.ExecContext(ctx, updateAutor,
		arg.IDAutor,
		arg.Nombre,
		arg.Pais,
		arg.FechaNacimiento,
		arg.Biografia,
	)
	return err
}
