// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: editorial.sql

package db

import (
	"context"
	"database/sql"
)

const createEditorial = `-- name: CreateEditorial :one
INSERT INTO Editorial (nombre, sede) 
VALUES ($1, $2) 
RETURNING id_editorial, nombre, sede
`

type CreateEditorialParams struct {
	Nombre string
	Sede   sql.NullString
}

func (q *Queries) CreateEditorial(ctx context.Context, arg CreateEditorialParams) (Editorial, error) {
	row := q.db.QueryRowContext(ctx, createEditorial, arg.Nombre, arg.Sede)
	var i Editorial
	err := row.Scan(&i.IDEditorial, &i.Nombre, &i.Sede)
	return i, err
}

const deleteEditorial = `-- name: DeleteEditorial :exec
DELETE FROM Editorial 
WHERE id_editorial = $1
`

func (q *Queries) DeleteEditorial(ctx context.Context, idEditorial int32) error {
	_, err := q.db.ExecContext(ctx, deleteEditorial, idEditorial)
	return err
}

const getEditorial = `-- name: GetEditorial :one
SELECT FROM Editorial 
WHERE id_editorial = $1
`

type GetEditorialRow struct {
}

func (q *Queries) GetEditorial(ctx context.Context, idEditorial int32) (GetEditorialRow, error) {
	row := q.db.QueryRowContext(ctx, getEditorial, idEditorial)
	var i GetEditorialRow
	err := row.Scan()
	return i, err
}

const listEditoriales = `-- name: ListEditoriales :many
SELECT id_editorial, nombre, sede FROM Editorial 
ORDER BY nombre
`

func (q *Queries) ListEditoriales(ctx context.Context) ([]Editorial, error) {
	rows, err := q.db.QueryContext(ctx, listEditoriales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Editorial
	for rows.Next() {
		var i Editorial
		if err := rows.Scan(&i.IDEditorial, &i.Nombre, &i.Sede); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEditorial = `-- name: UpdateEditorial :exec
UPDATE Editorial 
SET nombre = $2, sede = $3
WHERE id_editorial = $1
`

type UpdateEditorialParams struct {
	IDEditorial int32
	Nombre      string
	Sede        sql.NullString
}

func (q *Queries) UpdateEditorial(ctx context.Context, arg UpdateEditorialParams) error {
	_, err := q.db.ExecContext(ctx, updateEditorial, arg.IDEditorial, arg.Nombre, arg.Sede)
	return err
}
