// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lee.sql

package db

import (
	"context"
	"database/sql"
)

const createLee = `-- name: CreateLee :one
INSERT INTO Lee (id_usuario, id_libro, estado, resena) 
VALUES ($1, $2, $3, $4) 
RETURNING id_usuario, id_libro, estado, resena
`

type CreateLeeParams struct {
	IDUsuario int32
	IDLibro   int32
	Estado    sql.NullString
	Resena    sql.NullString
}

func (q *Queries) CreateLee(ctx context.Context, arg CreateLeeParams) (Lee, error) {
	row := q.db.QueryRowContext(ctx, createLee,
		arg.IDUsuario,
		arg.IDLibro,
		arg.Estado,
		arg.Resena,
	)
	var i Lee
	err := row.Scan(
		&i.IDUsuario,
		&i.IDLibro,
		&i.Estado,
		&i.Resena,
	)
	return i, err
}

const deleteLee = `-- name: DeleteLee :exec
DELETE FROM Lee 
WHERE id_usuario = $1 AND id_libro = $2
`

type DeleteLeeParams struct {
	IDUsuario int32
	IDLibro   int32
}

func (q *Queries) DeleteLee(ctx context.Context, arg DeleteLeeParams) error {
	_, err := q.db.ExecContext(ctx, deleteLee, arg.IDUsuario, arg.IDLibro)
	return err
}

const getLee = `-- name: GetLee :one
SELECT FROM Lee 
WHERE id_usuario = $1 AND id_libro = $2
`

type GetLeeParams struct {
	IDUsuario int32
	IDLibro   int32
}

type GetLeeRow struct {
}

func (q *Queries) GetLee(ctx context.Context, arg GetLeeParams) (GetLeeRow, error) {
	row := q.db.QueryRowContext(ctx, getLee, arg.IDUsuario, arg.IDLibro)
	var i GetLeeRow
	err := row.Scan()
	return i, err
}

const listLees = `-- name: ListLees :many
SELECT id_usuario, id_libro, estado, resena FROM Lee
`

func (q *Queries) ListLees(ctx context.Context) ([]Lee, error) {
	rows, err := q.db.QueryContext(ctx, listLees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lee
	for rows.Next() {
		var i Lee
		if err := rows.Scan(
			&i.IDUsuario,
			&i.IDLibro,
			&i.Estado,
			&i.Resena,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLee = `-- name: UpdateLee :exec
UPDATE Lee 
SET estado = $3, resena = $4
WHERE id_usuario = $1 AND id_libro = $2
`

type UpdateLeeParams struct {
	IDUsuario int32
	IDLibro   int32
	Estado    sql.NullString
	Resena    sql.NullString
}

func (q *Queries) UpdateLee(ctx context.Context, arg UpdateLeeParams) error {
	_, err := q.db.ExecContext(ctx, updateLee,
		arg.IDUsuario,
		arg.IDLibro,
		arg.Estado,
		arg.Resena,
	)
	return err
}
