// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: libro.sql

package db

import (
	"context"
	"database/sql"
)

const createLibro = `-- name: CreateLibro :one
INSERT INTO Libro (titulo, id_autor, id_editorial, fecha_lanzamiento, cantidad_paginas) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING id_libro, titulo, id_autor, id_editorial, fecha_lanzamiento, cantidad_paginas
`

type CreateLibroParams struct {
	Titulo           string
	IDAutor          sql.NullInt32
	IDEditorial      sql.NullInt32
	FechaLanzamiento sql.NullTime
	CantidadPaginas  sql.NullInt32
}

func (q *Queries) CreateLibro(ctx context.Context, arg CreateLibroParams) (Libro, error) {
	row := q.db.QueryRowContext(ctx, createLibro,
		arg.Titulo,
		arg.IDAutor,
		arg.IDEditorial,
		arg.FechaLanzamiento,
		arg.CantidadPaginas,
	)
	var i Libro
	err := row.Scan(
		&i.IDLibro,
		&i.Titulo,
		&i.IDAutor,
		&i.IDEditorial,
		&i.FechaLanzamiento,
		&i.CantidadPaginas,
	)
	return i, err
}

const deleteLibro = `-- name: DeleteLibro :exec
DELETE FROM Libro 
WHERE id_libro = $1
`

func (q *Queries) DeleteLibro(ctx context.Context, idLibro int32) error {
	_, err := q.db.ExecContext(ctx, deleteLibro, idLibro)
	return err
}

const getLibro = `-- name: GetLibro :one
SELECT id_libro, titulo, id_autor, id_editorial, fecha_lanzamiento, cantidad_paginas FROM Libro
WHERE id_libro = $1
`

func (q *Queries) GetLibro(ctx context.Context, idLibro int32) (Libro, error) {
	row := q.db.QueryRowContext(ctx, getLibro, idLibro)
	var i Libro
	err := row.Scan(
		&i.IDLibro,
		&i.Titulo,
		&i.IDAutor,
		&i.IDEditorial,
		&i.FechaLanzamiento,
		&i.CantidadPaginas,
	)
	return i, err
}

const listLibros = `-- name: ListLibros :many
SELECT id_libro, titulo, id_autor, id_editorial, fecha_lanzamiento, cantidad_paginas FROM Libro 
ORDER BY titulo
`

func (q *Queries) ListLibros(ctx context.Context) ([]Libro, error) {
	rows, err := q.db.QueryContext(ctx, listLibros)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Libro
	for rows.Next() {
		var i Libro
		if err := rows.Scan(
			&i.IDLibro,
			&i.Titulo,
			&i.IDAutor,
			&i.IDEditorial,
			&i.FechaLanzamiento,
			&i.CantidadPaginas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLibro = `-- name: UpdateLibro :exec
UPDATE Libro 
SET titulo = $2, id_autor = $3, id_editorial = $4, fecha_lanzamiento = $5, cantidad_paginas = $6
WHERE id_libro = $1
`

type UpdateLibroParams struct {
	IDLibro          int32
	Titulo           string
	IDAutor          sql.NullInt32
	IDEditorial      sql.NullInt32
	FechaLanzamiento sql.NullTime
	CantidadPaginas  sql.NullInt32
}

func (q *Queries) UpdateLibro(ctx context.Context, arg UpdateLibroParams) error {
	_, err := q.db.ExecContext(ctx, updateLibro,
		arg.IDLibro,
		arg.Titulo,
		arg.IDAutor,
		arg.IDEditorial,
		arg.FechaLanzamiento,
		arg.CantidadPaginas,
	)
	return err
}
