// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Autor struct {
	IDAutor         int32
	Nombre          string
	Pais            sql.NullString
	FechaNacimiento sql.NullTime
	Biografia       sql.NullString
}

type Editorial struct {
	IDEditorial int32
	Nombre      string
	Sede        sql.NullString
}

type Lee struct {
	IDUsuario int32
	IDLibro   int32
	Estado    sql.NullString
	Resena    sql.NullString
}

type Libro struct {
	IDLibro          int32
	Titulo           string
	IDAutor          sql.NullInt32
	IDEditorial      sql.NullInt32
	FechaLanzamiento sql.NullTime
	CantidadPaginas  sql.NullInt32
}

type Usuario struct {
	IDUsuario     int32
	NombreUsuario string
	Mail          string
	Contrasena    string
}
