// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuario.sql

package db

import (
	"context"
)

const createUsuario = `-- name: CreateUsuario :one
INSERT INTO Usuario (nombre_usuario, mail, contrasena) 
VALUES ($1, $2, $3) 
RETURNING id_usuario, nombre_usuario, mail, contrasena
`

type CreateUsuarioParams struct {
	NombreUsuario string
	Mail          string
	Contrasena    string
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUsuario, arg.NombreUsuario, arg.Mail, arg.Contrasena)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.NombreUsuario,
		&i.Mail,
		&i.Contrasena,
	)
	return i, err
}

const deleteUsuario = `-- name: DeleteUsuario :exec
DELETE FROM Usuario 
WHERE id_usuario = $1
`

func (q *Queries) DeleteUsuario(ctx context.Context, idUsuario int32) error {
	_, err := q.db.ExecContext(ctx, deleteUsuario, idUsuario)
	return err
}

const getUsuario = `-- name: GetUsuario :one
SELECT id_usuario, nombre_usuario, mail, contrasena FROM Usuario 
WHERE id_usuario = $1
`

func (q *Queries) GetUsuario(ctx context.Context, idUsuario int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, idUsuario)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.NombreUsuario,
		&i.Mail,
		&i.Contrasena,
	)
	return i, err
}

const listUsuarios = `-- name: ListUsuarios :many
SELECT id_usuario, nombre_usuario, mail, contrasena FROM Usuario 
ORDER BY nombre_usuario
`

func (q *Queries) ListUsuarios(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.IDUsuario,
			&i.NombreUsuario,
			&i.Mail,
			&i.Contrasena,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUsuario = `-- name: UpdateUsuario :exec
UPDATE Usuario 
SET nombre_usuario = $2, mail = $3, contrasena = $4
WHERE id_usuario = $1
`

type UpdateUsuarioParams struct {
	IDUsuario     int32
	NombreUsuario string
	Mail          string
	Contrasena    string
}

func (q *Queries) UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) error {
	_, err := q.db.ExecContext(ctx, updateUsuario,
		arg.IDUsuario,
		arg.NombreUsuario,
		arg.Mail,
		arg.Contrasena,
	)
	return err
}
